services:
 db:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: produtosdb
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   ports:
     - "3306:3306"
   volumes:
     - db_data:/var/lib/mysql


 web:
   build: .
   ports:
     - "5000:5000"
   depends_on:
     - db
   environment:
     DB_HOST: db
     DB_NAME: produtosdb
     DB_USER: user
     DB_PASSWORD: password

volumes:
  db_data:
